### ISSUE TITLE
PresetComposer feature: Duplicate selected scene

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#101]
Right clicking a scene (right clicking its name) could open a menu that let me duplicate it, insert it just below the scene I duplicated. The new scene should have the same name with a "_1" suffix after it.

Also, this right click menu should include the default New, Clear Scenes, Clear Actions and Refresh options because those are no longer accessible if the GUI is filled with scenes.

**Comment by DarienBrito** [comment]
Duplication is now possible. I don't do automatic name assignment because there are too many variables to consider, user has to provide a name. If same name as selected scene is given, it will append _copy to it. If given name is the same as another existing scene it will write selectedName+givenName and raise a warning in the console. Keeping track of all names and come up with a numbering system to prevent overwriting safely is way too boring to do, at least now :stuck_out_tongue:  User is responsible of giving good names for duplicates, specially if giving the same name as a scene that is not the one that was selected for duplication.
