### ISSUE TITLE
couple of tiny ones: default message on preset import, font list

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#106]
when you import presets, there's a dialogue with a str menu that says banana.tiff. I think maybe part of that is some default text left in?

there is a hard coded list of fonts in the yFx buttons, and unless you plan on  distributing them as well, maybe you should get rid of that so the button works if someone wants to extend the UI or otherwise reuse. Its a cool button, I like the simplicity of combining a lightweight button with what's essentially also a lightweight panel execute. 

Of course it would also be great to have that collection of fonts in the library perhaps, they all seem like what I'm guessing is a carefully curated list of Gerritsen brother text weapons, seem really nice and I'm particularly curious about this material icons set the settings button comes from...

**Comment by DarienBrito** [comment]
> when you import presets, there's a dialogue with a str menu that says banana.tiff. I think maybe part of that is some default text left in?

Solved.

> there is a hard coded list of fonts in the yFx buttons, and unless you plan on distributing them as well, maybe you should get rid of that so the button works if someone wants to extend the UI or otherwise reuse. Its a cool button, I like the simplicity of combining a lightweight button with what's essentially also a lightweight panel execute.

Ah yes, that's a good point. The only fonts that are used in TDMorph are MaterialDesign, OpenSans and SegoeUI, which I thought came with a standard TouchDesigner install, I am not sure about that, specially on MacOS, so need to check. Can you post a picture of how the UI looks for you? Please see if those three fonts I mentioned are available if you drop a text node in TD and look at the fonts menu... 

Now, If a user wants to extend beyond those all the user has to do is provide his/her own list of fonts to the custom parameter of the button. I'll get rid of all the fonts that are not in used after I do a full check of all UI elements.

> Of course it would also be great to have that collection of fonts in the library perhaps, they all seem like what I'm guessing is a carefully curated list of Gerritsen brother text weapons, seem really nice and I'm particularly curious about this material icons set the settings button comes from...

Nope. I'm definitely not gonna package all the listed fonts in that element. I don't own them and its a total overkill since I use only 3 different fonts. Maybe if Roy releases his UI stuff sometime then this button can be extended, but that is very secondary to TDMorph itself.

**Comment by drmbt** [comment]
Totally get it. I think it holds the gear from material design, changing any of the fonts breaks it. Should be ok if no one touches anything, and it's deep enough in there that fixing probably isn't absolutely necessary, but it might be nice to include the fonts you use somewhere

**Comment by DarienBrito** [comment]
MaterialDesign, OpenSans and SegoeUI

@drmbt Did you have this fonts above in your computer? I mean without having to install them manually from somewhere? I'm suspecting they come with TD...

@johannbl Can you also check?

**Comment by DarienBrito** [comment]
Closing this one and opening another issue with accurate naming, since issue refers to fonts.
