### ISSUE TITLE
ParPopup Settings focus

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#113]
I like the automatic close setting on the ParPopup window, it took a bit of snooping to find it. Perhaps it should be a default? 

I find that there is still a small problem with this window, being that its possible if you don't click it as the first thing to focus on after its creation, it can get stuck behind other windows or viewers. If you don't know that this has occurred, attempting to create another one won't work because there is already an open viewer behind your process. Maybe it should check and destroy any existing instances first? This isn't such a problem over your primary network editor, but if you work with multiple screens and have a GUI over there, it is a thing that i ran into a few times.

It would be nice if on automatic close, the newly generated ParPopup Settings window was also made to be in focus automatically. This way if you click off of it the window closes, as opposed to now where you still have to make it the in focus window first for the auto close function to trigger. I did some digging in the wiki but couldn't figure out an effective method for calling that floating window that was just generated and setFocus(), but i didn't try too hard. 

Another nice thing to avoid the menu from going off the screen if TDMorph is horizontally oriented to the right would be further offsetting its x axis. I found that an offset of about -215, -170 positions the mouse over the close button, which might be a nice touch...

**Comment by drmbt** [comment]
Might be a good idea in ParPopup to check if the window is open first, and if so close it before opening it. basically just add: 
if op("window").isOpen: 
    op("window").par.winclose.pulse()
op("window").par.winopen.pulse()

**Comment by DarienBrito** [comment]
> I like the automatic close setting on the ParPopup window, it took a bit of snooping to find it. Perhaps it should be a default?

No, it should not close automatically, this window should be closed explicitly. This window is not something one calls very often, when one does it is because there is something in particular one needs and needs focus. This window is to control things, not an exploratory or an aid thing, therefore its window hierarchy is high and will not auto-close.

> Might be a good idea in ParPopup to check if the window is open first, and if so close it before opening it. basically just add:
if op("window").isOpen:
op("window").par.winclose.pulse()
op("window").par.winopen.pulse()

Yes, definitely, this has been added in latest version.

> Another nice thing to avoid the menu from going off the screen if TDMorph is horizontally oriented to the right would be further offsetting its x axis. I found that an offset of about -215, -170 positions the mouse over the close button, which might be a nice touch...

I have adjust position so that it fits over wherever the TDMorph UI is without going overboard. I do not thing placing the cursor by default over the close button is a good idea.
