### ISSUE TITLE
PresetAnimator Suggestion. Let user pick which preset are used to generate the Animation

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#121]
It could be handy to be able to generate the animation with only a selection of presets rather than using them all. Along with this, being able to reorder the presets would also be useful.

A str parameter accepting a list of preset indexes (split by spaces or commas) could be used to select which preset to use in the getRaw data. It's not the fanciest solution but it would give more flexibility to this module. It seems this would happen in getAllChannels. I might be able to write this and pull request it.

**Comment by DarienBrito** [comment]
Ah, good idea! The PresetAnimator already does this under the hood using an invokation to an "PresetsOrder" list, taken from the PresetManager. That is this portion of the PresetAnimation extension code:

```
		# By default try to use the order stored order in PresetsManager but
		# do nothing if there are no entries in the given order.
		if useFoundOrder:
			order = op(self.ownerComp.par.Presetmanager).PresetsOrder
			if len(order) > 0:
				self.keys = order
```

The best way to achieve what you suggest would be to generalize this, so that it can be used both by the PresetManager automatically and by the users if some order is provided. I think your suggestion of passing an order as a list is perfectly fine.  So, if you wanna give it a shot, see how to expand that code so that it works flexibly in both cases.

**Comment by johannbl** [comment]
Oh I missed this bit. I'm still using beta1 for the instance with which I use the PresetAnimator. Did this change recently? I can't find the bit you refer to so I'm having a hard time understanding it without context. I would really like to give it a go.

**Comment by DarienBrito** [comment]
Yes this changed right before I did the stream. You can use the one I posted in the slack channel some days ago. Is called PrivateBetaUpdate3 I think.

**Comment by johannbl** [comment]
Oh wow. So this feature suggestion is already part of TDMorph. There's just not GUI for it. haha.

**Comment by DarienBrito** [comment]
Yeah pretty much :) FYI, I have added an extra security check  that prevents some errors in the very latest version, so you can work with this updated functions for the PresetAnimator Class if you want:

```
	def initialize(self, withData=None, useFoundOrder=True):		
		# One may supply a synthetic (made up) dictionary from where
		# to create key frames via withData. PresetComposer uses this 
		# for instance to create an animation from scenes with arbitrary
		# properties.
		if withData is not None:
			self.presets = withData
		else:
			self.presets 	= op(self.ownerComp.par.Presetmanager).Presets.getRaw()

		# Order is initially based on given dictionary's keys order
		self.keys = list(self.presets.keys()) 

		# By default try to use the order stored order in PresetsManager but
		# do nothing if there are no entries in the given order.
		if useFoundOrder:
			order = op(self.ownerComp.par.Presetmanager).PresetsOrder
			if len(order) > 0:
				self.keys = order

		# Check if valid
		if len(self.keys) > 0:
			# Create data for animation 
			self.channels 	= self.getAllChannels()
			self.groups 	= self.createParameterGroups()
			return True
		else:
			self.ReportResult('The current Preset Manager has not presets to make an animation from', 'Animation')
			return False
```
And replace the last lines of "CreateAnimation" with this:
```
		if valid:
			self.createChannels(target.op('channels'))
			frames = self.createKeyFrames(target.op('keys'))
			self.ownerComp.par.Totaldurationf = frames
			self.ownerComp.par.Totaldurations = frames / self.ownerComp.time.rate
		return
```

**Comment by DarienBrito** [comment]
Answering to your edit:

> edit: I found the code in beta3. I get it now. So if the PresetManager has a specified PresetsOrder, Animator is already built to use that order? This is great. So all that's missing is a way to set this order with the PresetManager and possibly a way to select just a section of this list (if we don't want to use all the presets?)

Yes, indeed. You must write the PresetsOrder yourself, this is not done automatically because that would not make sense. Best design to keep things totally modular would be to write this order from the tool that needs the order, so just a method from the PresetAnimator in this case that executes when an order is provided. 

You don't need to have a way to select just a section of the list. The list IS the definition, so whatever your write in the list will be used and what you don't write will be ignored. 

```
.PresetsOrder = ['1', '5'] # Will include only presets 1 and 5 
```
You can even do stuff like this:

```
.PresetsOrder = ['4, '2', '4', '5', '1'] # Will include one of the entries twice
```

**Comment by DarienBrito** [comment]
I have gone ahead and implemented this already ;) See below:

![Capture](https://user-images.githubusercontent.com/5923038/83747732-58330a80-a661-11ea-84dc-3076e632ae63.PNG)
