### ISSUE TITLE
PresetAnimator option to truncate the name of channels by level of path

### ISSUE THREAD

**Issue by ruigato** [DarienBrito/TDMorph#122]
right now when creating a PresetAnimator from a PresetComposer that has been fed by a PresetManager that is being populated via opFindDAT from diffent sources, the channel names assume the whole path of the parameters. Because Animaton Editor does not allow to resize the channel names column, its very hard to navigate in the created channels.

It would be really nice to be able to truncate the prefix of channel name by level of path depth

**Comment by DarienBrito** [comment]
Ah, good one!

This is rather tricky, because the full paths need to be know so that the animation can write directly to the parameters in an efficient way from a script. Because one could have the same name of parameters from different operators and because these all can come from any level, keeping track of levels and hierarchies is a bit of a nightmare and complicates the code disproportionally for the simple task this thing is meant to do.

The best solution I could think of is to create an "alias" for the parameters on the Animation editor, so what you see as a name there when editing curves is just: OperatorName+parameterName, so it will never be longer than that. All parameters get renamed outside of the Animation COMP to their full paths so that they can appropriately write where they should. If one has two operators named the same in different levels it can be a bit confusing, but one can always step out of the animation to check where a channel comes from in the Rename CHOP I have created, which is surely much more conveninent than super long absolute paths that no one can read ;) 

Solved.
