### ISSUE TITLE
beta3 Standalone PresetManager doesn't update .PresetsOrder as it should

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#124]
When creating presets with the main COMP, PresetsOrder is updated. PresetAnimator works right away.

However, when using the standalone PresetManagerCOMP, PresetsOrder is stuck at None when storing presets using the .StorePreset(target) command.

**Comment by DarienBrito** [comment]
No because that is not how this is meant to work. Presets Order is user defined, not automatic (would not make any sense to make it automatic since order is arbitrary and no order is just dictionary order). You have to write to it before doing operations like  this for instance:

.PresetOrder = ['1', '3', '5']

(See the ElementsContainer Presets for instance to see how it is used)

All TD morph elements that support order will try to look for PresetsOrder. If it doesn't exist or if its size is < 1, then they will simply use the dictionary order, which is entry-order.

**Comment by johannbl** [comment]
Hm I see.. but then could there be a default value? The main comp actually assigns a default value upon preset creation how come the PresetManager can't?

If not, then I'd advice that PresetAnimator doesn't default the useCustomOrder (not sure what the parameter name is) to True. It doesn't make sense to default this parameter to True when the default coming from PresetManager is to not generate an order. It creates a system that is broken by default.

**Comment by DarienBrito** [comment]
Ok, various innacuracies here:

> Hm I see.. but then could there be a default value? 

No, because that does not make sense from the programming perspective. I explain in the next points why.

> The main comp actually assigns a default value upon preset creation how come the PresetManager can't?

The main COMP does not assign any value the PresetsOrder, ElementsContainer does, and it only does so because one is able to change the order of presets in the UI. By default in presetManager  PresetOrder = [] , because it is not necessary to have any order for it to function.

Remember that PresetManager does never know (or needs to know) about UI's or high level things. PresetManager functions as a database, so it doesn't know anything about orders or buttons or stuff like that implicitly, because that is just bad programming. One needs to explicitly address that information from a higher level if wanted, because PresetManager should function by itself without any dependencies in any situation. So again, an order is not required for it to function, its just an option, so by default there's no order.

> If not, then I'd advice that PresetAnimator doesn't default the useCustomOrder (not sure what the parameter name is) to True.

The default is set to True because it is always preferable to look for a deliberate order of the presets than assuming the insertion order on a high level tool such as PresetAnimator, given that re-ordering is possible. 

> It doesn't make sense to default this parameter to True when the default coming from PresetManager is to not generate an order. It creates a system that is broken by default.

If you read carefully the logic in the code is not that it will always use a pre-defined order, it is that it will only do so if such order has a lenght > 0. Otherwise it defaults to the preset creation order. 

This is done in that way as a high-level convenince to always check implicitly first if an order has been supplied, favoring pulling orders from controllers that allow to do so (such as ElementsContainer and PresetComposer). PresetComposer is an interesting case where things have to be synthetically created and where  useCustomOrder=False. 

In general, the programming paradimg is that objects pull data from the database (PresetManager) and write data to it if they need it. But PresetManager should absolutely be at all times free of high-level information.

**Comment by DarienBrito** [comment]
Here the code in the current latest version for reference, with #121 implemented:

```python
	def initialize(self, withData=None, useFoundOrder=True):		
		# One may supply a synthetic (made up) dictionary from where
		# to create key frames via withData. PresetComposer uses this 
		# for instance to create an animation from scenes with arbitrary
		# properties.
		if withData is not None:
			self.presets = withData
		else:
			self.presets 	= op(self.ownerComp.par.Presetmanager).Presets.getRaw()

		# Order is initially based on given dictionary's keys order
		self.keys = list(self.presets.keys()) 

		# By default try to use the order stored order in PresetsManager but
		# do nothing if there are no entries in the given order.
		if useFoundOrder:
			if self.ownerComp.par.Usespecificpresets.eval():
				order = re.split('\\W+', self.ownerComp.par.Presetssequence.eval())
			else:
				order = op(self.ownerComp.par.Presetmanager).PresetsOrder
			# Only use order if there's data there	
			if len(order) > 0:
				self.keys = order

		# Check if valid
		if len(self.keys) > 0:
			# Create data for animation 
			self.channels 	= self.getAllChannels()
			self.groups 	= self.createParameterGroups()
			return True
		else:
			self.ReportResult('The current Preset Manager has not presets to make an animation from', 'Animation')
			return False
```
