### ISSUE TITLE
Report to TouchDesigner: Renaming TDMorph causes errors due to inner cloning bug in TD

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#134]
I'm not exactly sure what it doesn't like, but all of the elements in Lib go crazy if you rename TDMorph.  Undoing/renaming it to original doesn't fix it

**Comment by DarienBrito** [comment]
This is not a bug in TDMorph but a bug in TouchDesigner. If you reinit the extensions for all the faulty sliders then everyting is fine again. I think is because of cloning. It can be prevented by not cloning all the objects in "Elements", but that should not be the solution, because the real problem is a bug in TD. It's worth reporting this to them to see if can be fixed, because it will happen in other systems as well. I'll send them a not about it

**Comment by DarienBrito** [comment]
Perhaps I'll release TDMorph with these objects uncloned untill they fix this one.

**Comment by DarienBrito** [comment]
Very interesting! the cause of this problem was the popUpMenu Widget from TouchDesigner. Removing this object does not cause any more issues with extensions!

**Comment by drmbt** [comment]
does this mean that on createUIElement its no longer necessary to set element.componentCloneImmune = True? Is there anything to be gained by making the elements clone immune?

**Comment by DarienBrito** [comment]
Yes, security. TouchDesigner is not very stable with clones inside clones. Some weird errors often appear if not clone inmune.

**Comment by DarienBrito** [comment]
Seems that latest TD (2023.11510) has all cloning sorted out. I've thoroughly updated the system and TDMorph 3.1.0 will be lighter, faster and more robust (coming soon)
