### ISSUE TITLE
Scene Launcher drag and drop

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#135]
One of the first things that I find myself wanting to do is drag presets from the left lister onto the main panel. The fact that I get a satisfying plus icon on drag suggests that the UI wants me to be able to do this as well. Can we get a drop script to create a quick new Scene from dragging a preset? 

Other then that, I feel like the UI should have some sort of add button or similar to guide the user towards creating a scene. At the very least a hover help to indicate that right clicking will get you a new dialogue might be nice, since right click menus isn't a mechanism you're employing elsewhere in the TDMorph architecture. just a thought

**Comment by DarienBrito** [comment]
I think dropping for a preset is a good idea. I have added this. When you drop a preset it will still ask you to provide a name for the scene though, because these have to be unique names.

> Other then that, I feel like the UI should have some sort of add button or similar to guide the user towards creating a scene. 

No need for a buttonI think. The functionality is so simple that once you know you must right click on it to do stuff, an add button hanging somewhere in the UI becomes immediately redundant. 

> At the very least a hover help to indicate that right clicking will get you a new dialogue might be nice

A hover thing will be more annoying than useful because again, once you know you have to right click the hover info is just unncessary noise. Pop up help is only useful when there are many elements of the same kind and it is easy to forget what something does, like with the controls in the ElementsContainer.

> ... since right click menus isn't a mechanism you're employing elsewhere in the TDMorph architecture. just a thought

Not true the it is a mechanism not employed elsewhere. Right clicking is also used in the Elements Container to Reset, clear and rename presets, as well as for creating a script.

Using SceneLauncher is so simple that I think users will have enough common sense to get to the right click, even if by accident. Also, TDMorph has enough documentation on the making that makes this clear, so I don't see the need of adding any of this latter things.
