### ISSUE TITLE
PresetManager ignore list

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#149]
I feel like this might be the opposite of what I was asking for back in issue #119 , but may have a similar answer.

I'm finding myself wanting to add to the extPresetManager getParameterSelection() method a 

`blacklist = str(self.ownerComp.par.Blacklist).split()`
`params 		= [par for par in target.customPars if par.name not in blacklist]`

and a customPar Blacklist to PresetManager.

I've been using the PresetManager headless pointed at a parent container without the rest of TDMorph, and when there are many parameters in the container, the idea of ignoring parameters like resolution/aspect, or labels/comments seems better then manually naming every parameter you do want to use in the Parameterscope list. Does doing something like this make sense, or add too much overhead? Does it break anything I'm not thinking about?

**Comment by DarienBrito** [comment]
Right. This is one of those things that depend on perspective. From the ux point of view, it would not make sense to me to have both an inclusive and an exclusive control simultaneously in the PresetManager. If this were to be done I would instead make it one or the other, not two distinct fields. 

So, what I mean is that I would rather have a toggle that says "exclusive" or "inclusive" without adding any other controls to the Preset Manager such as "Blacklist". If exclusive, then whatever is in the scope is ignored, if inclusive, then taken into account. In this manner the behaviour is always consistent, unique and clean.

This will not break anything but will add one extra for loop to the  code. I don't think it will make much difference but on large projects every for loop counts, so that's something to be aware of...

On the other hand, you can also just have a script that takes care of the blacklisting before passing the values to the PresetManager. So with the script you just write in the scope the values that you need.

I have not yet personally encountered a situation where I would need something like what you describe, but let's leave this open in case others think is useful. For now I would suggest just writing a script that does this for you and then write normally into the parameter scope.

**Comment by DarienBrito** [comment]
This is solved in 3.1.0 with the very powerful regular expressions mechanism to filter parameters. Will not be done as blacklisting.
