### ISSUE TITLE
PresetManager morphingCompletion

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#158]
the second output of a PresetManager tox is meant to be morphingCompletion... it doesn't appear to be active. I'd imagine that was maybe something that was to be handled by the timer callback and hasn't been activated yet? or am i missing something, and that is spitting out a value from a function I'm not calling?

**Comment by DarienBrito** [comment]
Hi there, sorry for very late reply on this one... morphing completion should "flip" when a whole morphing set its done. It's not a pulse but a flip of whatever state it is on, because pulsing requires constant cooking which TDMorph avoids. Anyhow, I'll have a look in the next update because I wanted this to behave a bit different anyways ;)

**Comment by DarienBrito** [comment]
Morphing completion works as expected in latest
