### ISSUE TITLE
The save button for presets should be removed and replaced by a shift click of the “load preset” button

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#17]
Suggestion by Johann Baron Lanteigne:

The save button for presets should be removed and replaced by a shift click of the “load preset” button. Just like how it the preset object works in max msp. This might be a bit less intuitive for someone who has never used the tool but it saves a lot of space.

**Comment by drmbt** [comment]
This is tricky because having the option to midi map the replacement of a preset is nice, but my workaround has been to move the main preset recall buttons to the collapsible header, hiding the buttons. As it currently stands, it is quite easy to accidentally overwrite a preset by hitting the button beneath it

**Comment by DarienBrito** [comment]
Sounds like a good idea. Need to think of a nice way to do this keeping clarity and visibility when saving. Will think about it...

**Comment by DarienBrito** [comment]
Recall/Saving/Deleting is now much cleaner/space efficient. New way:
* Recalling: left click
* Saving: Shift + left click
* Deleting: Shift + right click

![Capture](https://user-images.githubusercontent.com/5923038/73120731-dbd14200-3f71-11ea-9135-129f90bd2823.PNG)

**Comment by jblanteigne** [comment]
Awesome!
