### ISSUE TITLE
insert preset between two consecutive

### ISSUE THREAD

**Issue by RobertoPuglieseFusco** [DarienBrito/TDMorph#173]
this is just a wish. Often I realize I want to create a preset to be positioned between two others. Although I could use the Alt+drag functionality to swap two presets, this becomes soon cumbersome when the list of presets is long.

**Comment by DarienBrito** [comment]
Thanks for the suggestion! Might be a tircky thing to add because of how the namings are handled for scenes. The choice to do the current mechanism was to be a ble to provide universality for the names across all of TDMorhp's suite... so this may not be a trivial addition. I will look into it though for upcoming updates!

**Comment by DarienBrito** [comment]
I've implemented now as an insertion indeed. 

If you drag and drop a button from lower to upper, it will insert after the dropped place: 1-2-3-4 (drag 1 over 2) 2-1-3-4
If you drag and drop from upper to lower, it will insert before the dropped place: 1-2-3-4 (drag 4 over 2) 1-4-2-3

Available in upcoming 3.1.0 version
