### ISSUE TITLE
TDMorph is broken with the new version of TD

### ISSUE THREAD

**Issue by baronlanteigne** [DarienBrito/TDMorph#179]
I'm sure you know but it's so unfortunate to rely on an older version of TD just to connect this tool with everything else.

Any plans to rebuild the tool? I have no idea how much work that could be but personally, I was a big fan of the PresetManager module!

Good luck with your projects.

**Comment by DarienBrito** [comment]
Yes! I have plans to rebuild it all, starting with PresetManager. I began work already on a TDMorph 3.0, which won't be backwards compatible unfortunately, but that will have very handy features and more flexibility for paths. Only thing is that it takes me a while because I'm quite busy will all sort of things and finding time spots to fully devote to it is difficult.

I perhaps will start by releasing PresetManager 3.0, so that at least this module is available. It is aferall the bedrock where all the engine rests upon ;) I'm not sure when I will be able to do it though,... perhaps as a christmas release?

**Comment by baronlanteigne** [comment]
Christmas sounds very appropriate haha! Thanks.

**Comment by markijzerman** [comment]
Hi Darien, also still love this module- it's a part of my _As Above, So Below_ performance show. I was hoping to run it on my new M1 Macbook Pro. Do you know if there's a TD version on which TDmorph still works smoothly and which supports the latest M1 processors? Or should I rewrite it to another solution? :)

**Comment by DarienBrito** [comment]
Hi Mark! 

I think it should still work with the latest 2020 series for sure. I think those did not work with M1 though and I'm not sure at what point in 2021 the package broke down... If you are in a hurry then maybe good to re-factor things. It should not be too hard to fix what's broken for your specific purpose, so I can give a hand with that as well if you want. Let me know in a DM in slack or something. 

If it can wait a bit, I'm now sure I'll have the new PresetManager system ready in December, and perhaps even the whole package of TDMorph 3.0 by end of the year.

**Comment by markijzerman** [comment]
Hi Darien! Thanks for your swift reply! I think for now I'll simply keep my PC with the old Touchdesigner around to perform the piece. But would love to use the refactored TDmorph at some point. I think mainly blending (that I rely on heavily) is definitely broken. Curious about TDmorph 3.0! :)

**Comment by DarienBrito** [comment]
Hey Mark, alright! More news about the status soon!

**Comment by DarienBrito** [comment]
Solved in latest version
