### ISSUE TITLE
Asterix * not stored on preset manager

### ISSUE THREAD

**Issue by tayotain** [DarienBrito/TDMorph#191]
Asterix * not stored on preset manager. 
its much needed on lights shadow caster selection and render settings.

**Comment by DarienBrito** [comment]
This is a tricky one. It is not possible to store asterix in parameters like "Geometry" or "Lights" directly, because that is a wildcard interpreted by the Object type paramter. These are not supported in TDMorph, because they do not reference an object, but is an expression that the parameter evaluates internally, and which result we don't have access to. You can tell if you do something like:

1) Drop a camera top
2) Create a text DAT
3) Write print(op('render1').par.geometry) and evaluate the text DAT
4) See the result in the console

You will see that it prints "None". But then if you add some geo COMPs and evaluate again, a list will be printed. 

None of this results can be used in TDMorph, because it expect either a valid parameter (not None) or a single parameter (not a list).

You can bypass this limitation  by:

1) Make a base with a custom string paramter
2) Make the render TOP reference that custom parameter.
3) Store the custom parameter in TDMorph

This works because in this case, the parameter is really a string, not an expression, so TDMorph is able to store and use it.

Hope that makes sense. Please keep an eye on TDMorph 3.1.0, which is coming out very soon ;) I can send an example network of how to address this issue as described aboved once the tool is released.
