### ISSUE TITLE
Extend locking to preset storing

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#21]
by jblanteigne:

Lock. This is a feature that I use a lot but I’ve implemented mine in a different way. Similar to the potential you’ve unlocked with Global/Local modes. I store my lock state with the presets. I call this bypass. Essentially if param1 is locked in preset2, it means whenever I launch preset2, the param1 value ignores the interpolation and sticks to its last value. This allows me to interpolate between different presets with the locked parameter while still being able to change this parameters with other “more global” presets. This creates new blends of presets similar to using two SlidersContainers but it also saves time when editing many presets.

**Comment by DarienBrito** [comment]
I am not sure I follow your suggestion. Is it that you want that a preset also stores the locked status on time of saving the preset? If this is the case, what would be the advantage of that over simply not moving the desired value for the next preset?

**Comment by DarienBrito** [comment]
Moving this to revision for V2

**Comment by jblanteigne** [comment]
Oh I somehow missed this. I suggested two different things there so let me clarify.

1) The lock/unlock status is stored within a preset meaning a specific preset that I absolutely do not want to edit by mistake can be locked whenever I interpolate to it. As soon as I interpolate to a different preset, the values will be unlocked again if that preset is unlocked. This is used as a protection.

2) This one is more creative. Instead of locking the whole preset, each individual parameter of each preset can be locked. I call this bypass because the transition will bypass the value of this parameter when a preset with locked parameters is "launched" In other words, each parameter retain the last value recalled. It's easier for me to explain with an example:

preset1:
- param1 val: 0.1
- param2 val: 0.1

preset2:
- param1 val: 0.2
- param2 val: 0.2

preset3:
- param1 val: 0.3
- param2 val: LOCKED

It behaves as follow: 

- I'm at Preset1. Both values are 0.1
- I switch to preset3, param1 is now 0.3 but param2 is locked so its value is still 0.1
- I switch to preset2, both values become 0.2
- I switch back to preset 3, now param2 retains its value of 0.2 while param1 behaves normally.

This means preset3 has two different outcome based on which preset was active before.

In a more complex setup, this allows the creation of presets that only alter some parameters while others are unaffected. A similar behavior could be created by splitting the parameters in different SliderContainers but this bypass approach will only "split" them when needed and offers more control over how parameters are grouped together.

**Comment by DarienBrito** [comment]
After thinking about this for a while and analyzing its pros and cons I have decided to do the following:

> The lock/unlock status is stored within a preset meaning a specific preset that I absolutely do not want to edit by mistake can be locked whenever I interpolate to it. As soon as I interpolate to a different preset, the values will be unlocked again if that preset is unlocked. This is used as a protection.

This will be added as an option for presets, so that one is able to lock a particular state, disabling editing possibilities for that preset.

> This one is more creative. Instead of locking the whole preset, each individual parameter of each preset can be locked. I call this bypass because the transition will bypass the value of this parameter when a preset with locked parameters is "launched" In other words, each parameter retain the last value recalled. It's easier for me to explain with an example:

I will not add this behaviour. Three reasons for this:

1. This behavior is not transparent, since it complicates things further by assuming relative values on change, which do not translate well to the simplicity of how lock is meant to work. This can lead to a lot of confusions when creating/recalling presets and defeats the purpose of "lock" as a high level convenience that bypasses morphing. 

2. It is marginal behaviour, meaning that the vast majority of users (including myself) will not expect the described mechanism out of the box.

3. Locking is a high level command, that is meant to help users block interpolation for a given parameter. It is not a core behaviour extendable to a UI-less use of the PresetManager. 

I am moving the first issue into a new dedicated one for clarity and closing this one.

**Comment by johannbl** [comment]
Understandable. It's a very niche case. I wonder if there is a way for me to build a module that could emulate something like this. Seems tricky. After a while messing with presets, I feel like one of the limitation of this approach is how every parameters are tied together, everything moves in sync. I guess the easiest work around is to split parameters in different sliderContainers. This is more intuitive. Also, on my side, this approach inspires me a different module meant to tie together multiple sliderContainers to achieve a similar effect.

**Comment by DarienBrito** [comment]
Let me know if you go further with that. Curious to see what approach you take.

**Comment by johannbl** [comment]
Here's a very rough demo of a preset launcher system using rules. It showcases three features:

1. A rule to trigger multiple sliderContainers at the same time; essentially associating two presets together.
2. A rule to cue a transition to another set of rules (warpTo) after a delay; turning your rules into a sequence.
3. The ability to list more than one warpTo destination so the sequence is less linear.

TDMorphComp gives me an error message when this system is running but it seems to be working properly.

[TDMorph_WarpTo_sketch.zip](https://github.com/DarienBrito/TDMorph/files/4452036/TDMorph_WarpTo_sketch.zip)
