### ISSUE TITLE
Warpt to

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#28]
This is a bit specific and maybe it deserves its own module controlling TDMorph but I still want to share this concept as I've been having a lot of fun with it.

Upon reaching its destination, a preset will automatically trigger the next transition towards another preset.

This value is stored with each preset along with a delay value. Here's an example:

Preset1, warpTo: 2, delay: 2s
Preset2, warpTo: 3, delay: 2s
Preset3, warpTo: 1, delay: 2s

This will chain together the 3 presets in order, waiting for 2 seconds between each transitions. It's usefull for presets that should "return home" after a little while.

Bonus: if you input more than one warpTo destinations, one of them will be picked at random. In the above example, this would be useful to break the chain.

**Comment by DarienBrito** [comment]
This cab be a nice addition indeed. It reminds me to some modular synthesizer sequencers... need to think how to integrate it without cluttering things and without complicating things for the user too much. Will look into it.

**Comment by jblanteigne** [comment]
I agree. I wonder if this kind of feature would work better as a separate .tox (or separate COMP at least). I think it would make sense to split performance and data entry. Some values are less likely to be edited when performing or editing your performance.

For reference, Here is how I've been organizing my presets.
![TouchDesigner099_2020-01-19_09-09-43](https://user-images.githubusercontent.com/10411890/72682519-b50b9b00-3a9b-11ea-8471-85bba6762df0.png)
Parameters are displayed elsewhere. Because the core of my workflow is giving custom names to my presets and organizing them so I can later export a timeline, I went with 1 horizontal line per preset, the name can be edited by clicking it as if it was a DAT cell. I use the arrow to launch a preset. There is an edit mode button that turn the arrow into smaller buttons that let me delete a preset, insert a new preset with current values below a target preset and move a preset one slot up.

I don't think this fits in your current design but I wanted to share this approach.

**Comment by DarienBrito** [comment]
I will deal with this by creating a satellite module that will handle this fine tuning stuff.  Not for coming update but for next major one.

**Comment by DarienBrito** [comment]
In addition, implement a system as in Ableton, where one can "cue" next cells in various ways.
