### ISSUE TITLE
Mapping for presets, random, morph

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#29]
Finally hooked up a midi controller with this as well, and immediately realized that the reason I want midi/osc control is to have quick tactile access to recalling presets, as well as the ability to map to morph and random for certain parameters. What would it take to implement midi/osc learn for these commands as well?

**Comment by DarienBrito** [comment]
I am not so keen on implementing auto learning for every single element in the UI because I foresee this will not very robust nor scalable in the future. It is not complicated to implement, but I am not sure I want to do that since the tool should remain very general. Will think about it.  

Note however that this is possible to do already in the current version by the user themselves using the provided high level API. It is a matter of writing as simple script for a change of MIDI note and using the high level commands described in TDMorph documentation:

`ClickUIRandomize()        # Clicks the randomize button`
`ClickUIMorph()            # Clicks the morph button`

And for a slider:

ClickUISliderRandomize()    # Triggers slider's randomization
ClickUISliderInterpolate()  # Triggers slider's morphing

I created this API so that this kind of things can be added when needed by the users.

**Comment by drmbt** [comment]
That makes sense, and I've already built some modules that do some of  this based on the thorough documentation you've provided. I am just putting it through all of the use cases that I have had for such a tool, which would act as a UI when working in Touch exclusively, but also offer the ability to be driven by Ableton or Resolume via OSC and MIDI, and would love this kind of information to piggy back on the JSON file as opposed to having to develop a second side car to store this functionality. 

I fully appreciate that MIDI and OSC were a later addition, and am grateful for however you decide it should work best, I'll adapt it to my workflow.

**Comment by DarienBrito** [comment]
Sure! Keep the suggestions coming! 😄 

> would love this kind of information to piggy back on the JSON file as opposed to having to develop a second side car to store this functionality.

This is interesting. Perhaps its a good idea to flag elements that have been mapped for proper book keeping... I'm adding another ticket for this specific suggestion.

**Comment by DarienBrito** [comment]
New issue created for this last bit. Closing this one.
