### ISSUE TITLE
MIDI piano, toggle and invert flags

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#31]
RFE for midi/OSC functionality to be modified based on trigger mode

**Comment by DarienBrito** [comment]
Could you further clarify this request? I don't follow what the suggested behaviour is.

**Comment by drmbt** [comment]
Perhaps this is a new module besides slidersContainer, but some sort of mechanism to designate whether a behavior should be a float (slider), bool (toggle) or Momentary in a mapping editor would be important to fully functional MIDI/osc implementation. Also, the ability to invert the range of the mapped midi so that the default of momentary triggers can be on and not off

**Comment by DarienBrito** [comment]
Closing this one because current behavior already allows users to send any MIDI message to supported controllers that will act according to input. TDMorph is not a MIDI manager, it just offers mappings as a convenience. So, any further MIDI processing needs to be done by the user prior to mapping it to TDMorph. The idea is: 

* MIDI->[processing]->TDMorph

And not:

* MIDI -> TDMorph -> [processing]
