### ISSUE TITLE
Sliders Container Methods Nomenclature

### ISSUE THREAD

**Issue by jblanteigne** [DarienBrito/TDMorph#40]
It took me a while to understand that the method used to launch a transition towards a specific preset was "SetUISetPreset(int)"

If the GUI is dumb, why is this called "SetUISetPreset"? Is it because the feature interacts with the GUI by simulating a click? Then why isn't it called ClickPreset(int)?

It should be named "SetPreset" or "LoadPreset".  I like the word "Launch" when it comes to this because it implies the time based interpolation.

I know changing these is sensitive but I feel like loading a preset is probably the most important method here, its name should be short and sweet.

**Comment by DarienBrito** [comment]
Methods ought to be named according to what they do. It is called  "SetUISetPreset" because:

1. "SetUI" is the prefix for all the methods that set some property of the UI, which is what this method does. It controls only the UI and does not interact directly with the PresetManager. All high level methods have this type of prefix.

2. The name "SetPreset" is already in use and us reserved for the main method in the PresetManager, which is in charge of actually doing so (see the extPresetManager class)

3. Short and sweet names as described are used in the PresetManager, which is the UI-Less object (see the extPresetManager class) not for high level commands.

This convention will not be changed.
