### ISSUE TITLE
LFO mode should follow range, and persist when inspector is closed

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#47]
Currently the LFO's range is 0-2, regardless of what is in the range parameters, until the range is changed. That means if you want it to scale to the default of the parameters range, you need to change it to something else and then back. That LFO should get those values on Create of the parameter.

It also seems that the LFO is only active while the inspector for that Par is open, and freezes wherever it was when you close the Inspector. That should persist I'd imagine

**Comment by DarienBrito** [comment]
I see! Yes, I forgot to set this range on creation, will fix. 

The reason why the LFO doesn't keep on playing on collapse is because I don't cook the nodes under the collapse to optimize resources. That's a dumb oversight! :P So I need to do that in a more fine grained manner. Will fix in the morning.

**Comment by drmbt** [comment]
I'd imagine your pattern implementation will make this unnecessary, but it would be nice to sync that LFO to a tempo being fed to the top level like the midi source operator

**Comment by DarienBrito** [comment]
This is fixed in V1.1.2. 

The previous comment is a different request. I'm moving that to its own issue. Closing this one.
