### ISSUE TITLE
Bind relative, or rebind command

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#54]
This is more of a question, or a conversation about best practices for how the TDmorph sliders should bind to a particular parameter. In 1.1, they create a bind reference based on the absolute path of the parameter, breaking the system if your network structure changes, or if you load the same configuration into another project with a different absolute path.

I think the best scenario would be to work with relative parameters, giving priority to Parent or Global shortcuts when at all possible. This way an instance of TDmorph could live inside custom toxes stored in the palette, and move between projects easily.

Ideally there would be some sort of way to reconnect parameters if the bound par moves or changes, the ability to drag a parameter onto a slider and update the binding of that particular slider. What do you think?

**Comment by DarienBrito** [comment]
That is a good point. I am already in the making of a manager for bindings, in a similar fashion to how MIDI mapping works with tables. In there you will be able to easily re-bind things. As for keeping things from breaking, I think something could be deviced if there are methods available in TD to keep track of changes granuarly (I think there are) so I will have a look. Adding this to following major update

**Comment by DarienBrito** [comment]
Working on this now. I don't see how one could create relative paths to the parameters, nor prioritize parent or global shortcuts, since there is no methods available in the Par or Op classes (as far as I can tell) that would return this information. Plus, it would be a hell of a task (and really boring) to try to implement a relative path solver... so no, not doing that.

The way to handle this issue will be with the bindings table. Not such a big deal to correct some paths by hand with a decent code editor when migrating projects, or changing node locations. In this case, If the user changes things in his/her network, then the user is responsible to correct the paths in the table.

**Comment by DarienBrito** [comment]
Done in V2.0. Now possible to re-bind by editing a Bindings Table in a similar fashion to how MIDI and OSC mapping works. You can invoke this table from the SlidersContainer parameters.
