### ISSUE TITLE
V1.1.2 - Bug - changing global time value during a transition will affect the output.

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#59]
How to reproduce:

- In Global mode, store a longer transition time to one of your preset.
- Launch a transition to this preset.
- During the transition, change the global time parameter to a different value.
- The transition will be stopped and values from the previous preset will be loaded instead.

**Comment by DarienBrito** [comment]
Changed the way that morphing time is set from a push-based approach to a pull based one, using a custom parameter. This prevents current TD behaviour of the clock totally not cooking on passing of a param if de-activated, while maintaining the efficiency of idle clocks not being activated needlessly.  Best of both worlds :)  

As a result, now all PresetManagers have a binding to their morphtime custom parameters.

Fixed in V1.1.3
