### ISSUE TITLE
Preset Manager Setter sorting alphabetically

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#62]
I'm noticing that presets are sorting themselves alphabetically in the preset manager, and not in order in which they were created. Since the Setting page recalls the Target from a drop down menu, these should probably be either sortable, the order be editable, or the sorting happen in order of creation, because it will make it very difficult to build a gui or map the recall of these presets in a meaningful way if the index changes based on the name given. Even for example creating presets named 'preset_[1-16] will sort with 1, [1-16], [2-9]. 

Maybe the Lister could be implemented so that we can determine the order they should be in, and recall the items that way?

**Comment by DarienBrito** [comment]
Yes, alphabetic sorting of presets happens because if you name your presets it doesn't make sense to create "1" then "8" and finally "2" and see a menu that says 1, 8, 2, or 
"a", "c", "d", or whatever. Whenever you have properly named presets,  you want the order of this things sorted. Also simply because if you name things like "acid" and have (n-1) presets and then finally "zebra", you want alphabetic order to be able to find your things in the menu easily.

Now, it doesn't really matter that they are sorted or not, because the way on which you recall your presets is not by index, but by name. So something like:

- recallPreset("2"), not recallPreset(2)
- recallPreset("c"), not recallPreset(3)
- recallPreset("zebra"), not recallPreset(n)

So, if you are building a UI on top of the PresetManager, you should not use index numbers from the menu, you should use the given menuLabels. 

Does that make sense? 

Indeed a PresetEditor is in my plans, so on the next version there will be a lot of possibilities to edit presets in a finer detail :smile:
