### ISSUE TITLE
Store LFO state and frequency with preset

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#63]
I suppose this is a matter of philosophy, but it would be really nice to animate certain parameters with the lfo at a specific speed, and recall the frequency and state of the Active LFO with any presets.

**Comment by DarienBrito** [comment]
Mmm... I'm not sure about this one. Let me think about it.

**Comment by DarienBrito** [comment]
Ok, what will be done in next major update is the addition of a toggle, that allows the user to select if the freq and time are to be stored in the presets.

**Comment by drmbt** [comment]
Brilliant

**Comment by DarienBrito** [comment]
Upon revision, this is actually very tricky and unwise  to do, because presets are destined to single objects. In the case of the UI, that is sliders, so data cannot be easily added to them without doing a major architectural change to the core library. I will not that, since priority is to support UI-less behaviour. TD will remember anyways last states of UI elements, so that data will not be lost on opening/closing. I also kind of like that signals are not storable in the same manner as values. This goes along the general situation of modular synthesis, which invites for exploration and accidents. Closing this one for these reasons.
