### ISSUE TITLE
V1.1.4 Accessing morph time in PresetsGrabber

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#73]
Not really a bug or a suggestion. I just want to discuss the possible need to access the morph time parameters (both the "global time" and "per slider time") in the PresetGrabber node. I know it's possible to fetch this data from the PresetManager parameter and from the MorphSettings parameter but are those values stored elsewhere? I realize that's a lot of data to fetch and a dedicated ParametersGrabber might be overkill.

**Comment by DarienBrito** [comment]
Yes. 

1. V1.1.4 allows to invoke all the presets data by calling you container and then accessing the Presets property. You need to invoke the .getRaw() on the Presets because they are a DependableDictionary, which has its own quirks. getRaw() gives you the normal dictionary version. Notice that each preset is an array of arrays of dictionaries. When dealing with UI elements this arrays are always of size 1. This is why you need to do [0][0] when accessing the property. Finally, pass the information you want. In your case: 'time'

```
container = op('TDMorph').GetContainer(1)
manager = container.GetPresetManager()
presets = manager.Presets.getRaw() # get dict from dependable
time = presets['1'][0][0]['time'] # access preset 1 time information
print(time)
```
1. If you dont want to write all this code. Then simply use the PresetGrabber. It gives you tables with all the information per preset. Like what I did with your XYSlider.

Now, to have the values per slider, you just need to access each sliders local PresetManager (there is one in each slider as well). So you can do:

```
container = op('TDMorph').GetContainer(1)
slider = container.GetSlider(1)
manager = slider.GetPresetsManager()
presets = manager.Presets.getRaw()
print(presets)
```

Finally, if all you want is the current time in each slider (or any other specific information such as curve and so on) then the best way is what you already said. Simply grab it from their PresetManager's parameters:

```
container = op('TDMorph').GetContainer(1)
slider = container.GetSlider(1)
manager = slider.GetPresetsManager()
print(manager.par.Morphtime)
```

**Comment by johannbl** [comment]
Ah, I see. The getRaw() is what I was looking for then. Thank you. Can't wait to see V2.0
