### ISSUE TITLE
Customizing the ElemuentUI doesn't push values to Elements

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#86]
It looks like what happens under the hood when you customize the ElementUI in Lib is the values and defaults get pushed to the individual Elements in the Lib/Elements folder. It looks like min/max and defaults are getting pushed properly, but the values themselves don't change, so new parameters don't inherit the values that had been set. Let me know if this makes sense, or if I need to make an example... can easily be replicated by adding a new parameter to ElementUI customPars and change the default value. New parameters added to TDMorph won't have the updated information

**Comment by DarienBrito** [comment]
Yes, naturally, because all the items inside the Elements base are clones of ElementUI1. You can see that everything inside ElementUI1 is cloned except for the "element" Widget, which is a special unique widget per data type. Now, TouchDesigner cloning does not clone custom parameters on the parent level. If you want to have something custom in your elements you need to add those by hand to relevant data types inside the Elements base.

**Comment by DarienBrito** [comment]
Closing this one. Use the approach described above to achieve propagation.
