### ISSUE TITLE
slider transition length isn't stored automatically as it should.

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#88]
Local mode per slider transition length requires a preset to be saved somewhere for it to update even though those values are supposed to apply to all presets. This leads to situations where the transition behavior is different as to what the parameters display.

**Comment by DarienBrito** [comment]
Not sure I'm getting what you mean. Could you write a series of steps to replicate the issue?

**Comment by johannbl** [comment]
Sure.

In local mode, changing the length parameter of a slider usually won't work unless you store a preset immediately after changing the value.

To reproduce, switch to local mode, change the length of a slider and trigger a preset transition. The new value will be shown on the slider but it won't be the one used for the transition. Now, because you just launched a transition, even storing a preset won't fix the issue. You will be stuck with the previous value being valid for how long the slider takes to morph but the displayed value in the GUI will be whatever you wrote down there.

In order to change the length parameter of a slider, you have to set a new desired value and store any preset. Then the displayed value in the GUI will match the actual values used for morphing.

**Comment by DarienBrito** [comment]
Ok, I think I have fixed this. There was indeed some nastiness going on inside because I had a remainder from previous version with strange referencing. Now doing what you describe results in the desired behaviour, which is that in local mode any preset triggering will use the length written in the UI field for each slider. No need to do strange things like storing a new preset, changing the value will immediately have an effect if you trigger a preset.
