### ISSUE TITLE
Signal Functionality

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#91]
It looks like what's happening is that TransportSatellite breaks down your beat into different resetSync messages that resets the LFO. I think your manual mode is the only one of these you need, and the other modes should be dynamically changing the frequency of the LFO to read only, and updating it to Bpm/cookRate so that the cycle of the LFO. This way it stays synced to the beat input, not just an independent LFO that gets synced... very similar to how an LFO behaves in ableton's manual or synced modes.

The way it currently is, Bar and Pulse both trigger on the downbeat, which is the same functionality of Beat set to beat 0. What I would really want is Beat meaning a pulse on each Beat value change(quarter note), with an option for 1/8th, 16th etc. 

For an example of what I'm talking about, the Bpmsync module of the project i sent you should behave this way, especially when paired with the Envelope option

**Comment by DarienBrito** [comment]
Ah yes. What you describe is already the intended functionality, there were some bugs in there while I was showing you how this is supposed to work in the chat, but I'm aware of it. ;) Working on it.

**Comment by DarienBrito** [comment]
This is solved. I'm quite happy with how it turned out. Code is much cleaner and now this control is much more flexible. You can enter any fraction value and the lfo will sync to that in the frame of the current BPM. so setting 1 for beat means 1 cycle per beat, 0.5 means 2 cycles in 1 beat), 0.25 means 4 cycles in 1 beat, 0.33 means 3 cycles in one beat, etc. Same for bars, 2  means 1 cycle in 2 bars, 3 1 cycle in 3 bars, etc.

 I am not gonna disable the freq for the LFO for now though, even when its being synced to a beat, for the sake of completion.
